// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: find_all_contact_response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_find_5fall_5fcontact_5fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_find_5fall_5fcontact_5fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_find_5fall_5fcontact_5fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_find_5fall_5fcontact_5fresponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_find_5fall_5fcontact_5fresponse_2eproto;
namespace find_all_contact_response {
class FindAllContactResponse;
struct FindAllContactResponseDefaultTypeInternal;
extern FindAllContactResponseDefaultTypeInternal _FindAllContactResponse_default_instance_;
class PeopleInfo;
struct PeopleInfoDefaultTypeInternal;
extern PeopleInfoDefaultTypeInternal _PeopleInfo_default_instance_;
}  // namespace find_all_contact_response
PROTOBUF_NAMESPACE_OPEN
template<> ::find_all_contact_response::FindAllContactResponse* Arena::CreateMaybeMessage<::find_all_contact_response::FindAllContactResponse>(Arena*);
template<> ::find_all_contact_response::PeopleInfo* Arena::CreateMaybeMessage<::find_all_contact_response::PeopleInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace find_all_contact_response {

// ===================================================================

class PeopleInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:find_all_contact_response.PeopleInfo) */ {
 public:
  inline PeopleInfo() : PeopleInfo(nullptr) {}
  ~PeopleInfo() override;
  explicit PROTOBUF_CONSTEXPR PeopleInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PeopleInfo(const PeopleInfo& from);
  PeopleInfo(PeopleInfo&& from) noexcept
    : PeopleInfo() {
    *this = ::std::move(from);
  }

  inline PeopleInfo& operator=(const PeopleInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeopleInfo& operator=(PeopleInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeopleInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PeopleInfo* internal_default_instance() {
    return reinterpret_cast<const PeopleInfo*>(
               &_PeopleInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PeopleInfo& a, PeopleInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PeopleInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeopleInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeopleInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PeopleInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PeopleInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PeopleInfo& from) {
    PeopleInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeopleInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "find_all_contact_response.PeopleInfo";
  }
  protected:
  explicit PeopleInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 1,
    kNameFieldNumber = 2,
  };
  // string uid = 1;
  void clear_uid();
  const std::string& uid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uid();
  PROTOBUF_NODISCARD std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  private:
  const std::string& _internal_uid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:find_all_contact_response.PeopleInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_find_5fall_5fcontact_5fresponse_2eproto;
};
// -------------------------------------------------------------------

class FindAllContactResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:find_all_contact_response.FindAllContactResponse) */ {
 public:
  inline FindAllContactResponse() : FindAllContactResponse(nullptr) {}
  ~FindAllContactResponse() override;
  explicit PROTOBUF_CONSTEXPR FindAllContactResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FindAllContactResponse(const FindAllContactResponse& from);
  FindAllContactResponse(FindAllContactResponse&& from) noexcept
    : FindAllContactResponse() {
    *this = ::std::move(from);
  }

  inline FindAllContactResponse& operator=(const FindAllContactResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FindAllContactResponse& operator=(FindAllContactResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FindAllContactResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const FindAllContactResponse* internal_default_instance() {
    return reinterpret_cast<const FindAllContactResponse*>(
               &_FindAllContactResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FindAllContactResponse& a, FindAllContactResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FindAllContactResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FindAllContactResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FindAllContactResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FindAllContactResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FindAllContactResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FindAllContactResponse& from) {
    FindAllContactResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FindAllContactResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "find_all_contact_response.FindAllContactResponse";
  }
  protected:
  explicit FindAllContactResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContactsFieldNumber = 3,
    kErrorDescFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // repeated .find_all_contact_response.PeopleInfo contacts = 3;
  int contacts_size() const;
  private:
  int _internal_contacts_size() const;
  public:
  void clear_contacts();
  ::find_all_contact_response::PeopleInfo* mutable_contacts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::find_all_contact_response::PeopleInfo >*
      mutable_contacts();
  private:
  const ::find_all_contact_response::PeopleInfo& _internal_contacts(int index) const;
  ::find_all_contact_response::PeopleInfo* _internal_add_contacts();
  public:
  const ::find_all_contact_response::PeopleInfo& contacts(int index) const;
  ::find_all_contact_response::PeopleInfo* add_contacts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::find_all_contact_response::PeopleInfo >&
      contacts() const;

  // string error_desc = 2;
  void clear_error_desc();
  const std::string& error_desc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_desc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_desc();
  PROTOBUF_NODISCARD std::string* release_error_desc();
  void set_allocated_error_desc(std::string* error_desc);
  private:
  const std::string& _internal_error_desc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_desc(const std::string& value);
  std::string* _internal_mutable_error_desc();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:find_all_contact_response.FindAllContactResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::find_all_contact_response::PeopleInfo > contacts_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_desc_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_find_5fall_5fcontact_5fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PeopleInfo

// string uid = 1;
inline void PeopleInfo::clear_uid() {
  _impl_.uid_.ClearToEmpty();
}
inline const std::string& PeopleInfo::uid() const {
  // @@protoc_insertion_point(field_get:find_all_contact_response.PeopleInfo.uid)
  return _internal_uid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeopleInfo::set_uid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:find_all_contact_response.PeopleInfo.uid)
}
inline std::string* PeopleInfo::mutable_uid() {
  std::string* _s = _internal_mutable_uid();
  // @@protoc_insertion_point(field_mutable:find_all_contact_response.PeopleInfo.uid)
  return _s;
}
inline const std::string& PeopleInfo::_internal_uid() const {
  return _impl_.uid_.Get();
}
inline void PeopleInfo::_internal_set_uid(const std::string& value) {
  
  _impl_.uid_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_uid() {
  
  return _impl_.uid_.Mutable(GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_uid() {
  // @@protoc_insertion_point(field_release:find_all_contact_response.PeopleInfo.uid)
  return _impl_.uid_.Release();
}
inline void PeopleInfo::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  _impl_.uid_.SetAllocated(uid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uid_.IsDefault()) {
    _impl_.uid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:find_all_contact_response.PeopleInfo.uid)
}

// string name = 2;
inline void PeopleInfo::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PeopleInfo::name() const {
  // @@protoc_insertion_point(field_get:find_all_contact_response.PeopleInfo.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeopleInfo::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:find_all_contact_response.PeopleInfo.name)
}
inline std::string* PeopleInfo::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:find_all_contact_response.PeopleInfo.name)
  return _s;
}
inline const std::string& PeopleInfo::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PeopleInfo::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_name() {
  // @@protoc_insertion_point(field_release:find_all_contact_response.PeopleInfo.name)
  return _impl_.name_.Release();
}
inline void PeopleInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:find_all_contact_response.PeopleInfo.name)
}

// -------------------------------------------------------------------

// FindAllContactResponse

// bool success = 1;
inline void FindAllContactResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool FindAllContactResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool FindAllContactResponse::success() const {
  // @@protoc_insertion_point(field_get:find_all_contact_response.FindAllContactResponse.success)
  return _internal_success();
}
inline void FindAllContactResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void FindAllContactResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:find_all_contact_response.FindAllContactResponse.success)
}

// string error_desc = 2;
inline void FindAllContactResponse::clear_error_desc() {
  _impl_.error_desc_.ClearToEmpty();
}
inline const std::string& FindAllContactResponse::error_desc() const {
  // @@protoc_insertion_point(field_get:find_all_contact_response.FindAllContactResponse.error_desc)
  return _internal_error_desc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FindAllContactResponse::set_error_desc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_desc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:find_all_contact_response.FindAllContactResponse.error_desc)
}
inline std::string* FindAllContactResponse::mutable_error_desc() {
  std::string* _s = _internal_mutable_error_desc();
  // @@protoc_insertion_point(field_mutable:find_all_contact_response.FindAllContactResponse.error_desc)
  return _s;
}
inline const std::string& FindAllContactResponse::_internal_error_desc() const {
  return _impl_.error_desc_.Get();
}
inline void FindAllContactResponse::_internal_set_error_desc(const std::string& value) {
  
  _impl_.error_desc_.Set(value, GetArenaForAllocation());
}
inline std::string* FindAllContactResponse::_internal_mutable_error_desc() {
  
  return _impl_.error_desc_.Mutable(GetArenaForAllocation());
}
inline std::string* FindAllContactResponse::release_error_desc() {
  // @@protoc_insertion_point(field_release:find_all_contact_response.FindAllContactResponse.error_desc)
  return _impl_.error_desc_.Release();
}
inline void FindAllContactResponse::set_allocated_error_desc(std::string* error_desc) {
  if (error_desc != nullptr) {
    
  } else {
    
  }
  _impl_.error_desc_.SetAllocated(error_desc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_desc_.IsDefault()) {
    _impl_.error_desc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:find_all_contact_response.FindAllContactResponse.error_desc)
}

// repeated .find_all_contact_response.PeopleInfo contacts = 3;
inline int FindAllContactResponse::_internal_contacts_size() const {
  return _impl_.contacts_.size();
}
inline int FindAllContactResponse::contacts_size() const {
  return _internal_contacts_size();
}
inline void FindAllContactResponse::clear_contacts() {
  _impl_.contacts_.Clear();
}
inline ::find_all_contact_response::PeopleInfo* FindAllContactResponse::mutable_contacts(int index) {
  // @@protoc_insertion_point(field_mutable:find_all_contact_response.FindAllContactResponse.contacts)
  return _impl_.contacts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::find_all_contact_response::PeopleInfo >*
FindAllContactResponse::mutable_contacts() {
  // @@protoc_insertion_point(field_mutable_list:find_all_contact_response.FindAllContactResponse.contacts)
  return &_impl_.contacts_;
}
inline const ::find_all_contact_response::PeopleInfo& FindAllContactResponse::_internal_contacts(int index) const {
  return _impl_.contacts_.Get(index);
}
inline const ::find_all_contact_response::PeopleInfo& FindAllContactResponse::contacts(int index) const {
  // @@protoc_insertion_point(field_get:find_all_contact_response.FindAllContactResponse.contacts)
  return _internal_contacts(index);
}
inline ::find_all_contact_response::PeopleInfo* FindAllContactResponse::_internal_add_contacts() {
  return _impl_.contacts_.Add();
}
inline ::find_all_contact_response::PeopleInfo* FindAllContactResponse::add_contacts() {
  ::find_all_contact_response::PeopleInfo* _add = _internal_add_contacts();
  // @@protoc_insertion_point(field_add:find_all_contact_response.FindAllContactResponse.contacts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::find_all_contact_response::PeopleInfo >&
FindAllContactResponse::contacts() const {
  // @@protoc_insertion_point(field_list:find_all_contact_response.FindAllContactResponse.contacts)
  return _impl_.contacts_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace find_all_contact_response

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_find_5fall_5fcontact_5fresponse_2eproto
